name    'lexance-hosts'
version '1.0.5'
source 'git://github.com/lexance/puppet-hosts.git'
author 'lexance'
license 'Apache License, Version 2.0'
summary 'UNKNOWN'
description 'Manage (dualstack-)hosts in /etc/hosts.'
project_page 'https://github.com/lexance/puppet-hosts'
dependency 'puppetlabs/stdlib', '>= 4.2.0'
dependency 'puppetlabs/concat', '>= 1.0.4'
